spring:
  application:
    name: recipes
  flyway:
    enabled: true
    user: &database-username admin
    password: &database-password admin
    url: &url jdbc:sqlite:src/main/resources/database/database.db
    locations: classpath:database/migrations
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
  datasource:
    url: *url
    driver-class-name: org.sqlite.JDBC
    username: *database-username
    password: *database-password
  graphql:
    graphiql:
      enabled: true